site_name: SHACL-X
theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.code.annotation
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue
      accent: lime

nav:
  - Home: 'index.md'
  - API: 'api.md'
  - X as RDF: 'rdf.md'
  - Functions: 'functions.md'
  - Constraints: 'constraints.md'
  - Rules: 'rules.md'

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shacl-x/shacl-x

plugins: 
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions: 
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables

copyright: |
  &copy; 2024 <a target="_blank" rel="noopener" href="https://ashleycaselli.github.io/">Ashley Caselli</a>